### PR TITLE
[FIX] fix compile on ubuntu18.04 + use anonymous namespace for hardco…

### PR DESCRIPTION
**Pull request by Simonhancrew**
### Problem Summary:

1. comile error on ubuntu18.04, `BRPC/src/brpc/redis_command.cpp:411:29: error: ‘numeric_limits’ is not a member of ‘std’`
2. CTX_WIDTH should in anonymous namespace, only used in this cpp file.

### Changed:

1. compile on ubuntu18.04, redis_commands.cpp use numeric_limits<>, while missing <limits> header, cause compile error
2. use anonymous namespace for hardcode var, dont emit this to brpc namespace

Side effects:

+ no side effect

### CODE REVIEW

**Comment by Simonhancrew** [comment]
@wwbmmm 烦请老哥take a look, 谢谢
