### PR TITLE
fix: define fallback `GFLAGS_NS=google` in config headers and remove the need of passing the `-DGFLAGS_NS=google` flags

### PR DESCRIPTION
**Pull request by chenrui333**
### What problem does this PR solve?

seeing some regression build failure in https://github.com/Homebrew/homebrew-core/pull/204308

```
/opt/homebrew/Cellar/brpc/1.12.0/include/butil/reloadable_flags.h:63:9: error: use of undeclared identifier 'GFLAGS_NS'
   63 |     if (GFLAGS_NS::RegisterFlagValidator(flag, validate_fn)) {
      |         ^
```

It would be just better to define `GFLAGS_NS=google` in config headers

### What is changed and the side effects?

Changed:

Side effects:
- Performance effects(性能影响):

- Breaking backward compatibility(向后兼容性): 

---
### Check List:
- Please make sure your changes are compilable(请确保你的更改可以通过编译).
- When providing us with a new feature, it is best to add related tests(如果你向我们增加一个新的功能, 请添加相关测试).
- Please follow [Contributor Covenant Code of Conduct](https://github.com/apache/brpc/blob/master/CODE_OF_CONDUCT.md).(请遵循贡献者准则).

### CODE REVIEW

**Comment by chenrui333** [comment]
relates to https://github.com/apache/brpc/pull/2877

**Comment by chenBright** [comment]
In my opinion, it is better to use GFLAGS_NAMESPACE instead of GFLAGS_NS.

**Comment by chenBright** [comment]
The issue has been fixed in in #2877 .
